# This is a basic workflow to help you get started with Actions

name: workflow1

on:

  push:


jobs:
  
  construir:

    runs-on: ubuntu-latest
    # Variables de entorno
    env:
      platform: azure
      region: us-west
      acount: 123456

    steps:
    

      - name: Hola Mundo
        run: echo Hello, world!
      
      - name: mi accion
        uses: .github/actions/my-action
      
      - name: Checkout
        uses: actions/checkout@v5.0.0

      - name: Setup PHP Action
        uses: shivammathur/setup-php@2.35.5
        with: 
          php-version: '8.3'

      - name: Setup Node.js environment
        uses: actions/setup-node@v5.0.0
        with: 
          node-version: lastest

      - name: Listar
        run: ls -la

      - name: Instalar paquetes
        run: chmod +x script.sh
          ./script.sh

      

      #- name: Imprimir multiples lineas
      #  if: ${{env.platform == 'azure'}}

      #  run: |
      #    echo "Valor de la plataforma: ${{env.platform}}"
      #    echo "Valor de la region: ${{env.region}}"
      #    echo "Valor de la cuenta: ${{env.acount}}"
      #    echo "Valor de la GithubAction: $GITHUB_ACTION"
      #    echo "Valor de la Actor: $GITHUB_ACTOR"
  
  #deployar:

  #  runs-on: ubuntu-latest
  #  needs: construir

  #  steps:
    
  #    - name: Hola Mundo
  #      run: echo Hello, world!

  #    - name: Imprimir multiples lineas
  #      run: |
  #        echo Add other actions to build,
  #        echo test, and deploy your project.